apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name2 }}
spec:
  replicas: {{ .Values.deployment.replicas2 }}
  selector:
    matchLabels:
      app: nginx2
  template:
    metadata:
      labels:
        app: nginx2
    spec:
      containers:
        - name: nginx2
          image: {{ .Values.deployment.image2 }}:{{ .Values.deployment.tag2 }}
          ports:
            - containerPort: {{ .Values.deployment.containerPort2 }}
---